#- name: log into docker hub registry 
#  become: yes
#  docker_login:
#   username: amineturki
#   password:  
- name: Tag image
  become: yes
  shell: 
  docker tag amineturki/myapp-cd amineturki/cd:latest
  
- name : Push image to DockerHub 
 become: yes
 shell:
 docker push  amineturki/cd
