- name: Tag and push to docker hub
  become: true
  docker_image:
    name: myapp-cd:latest
    repository: https://registry.hub.docker.com/amineturki/cd
    tag: 7.0
    push: yes
    state : present
