- name: log into docker hub registry
  docker_login:
    username: amineturki
    password: 181JMT1811

- name: Tag and push to docker hub
  become: true
  docker_image:
    name: myapp-cd:latest
    repository: https://registry.hub.docker.com/amineturki/cd
    tag: 7.0
    push: yes
    state : present
