- name: log into docker hub registry 
  become: yes
  docker_login:
   username: amineturki
   password: 181JMT1811   
- name: Tag and push to docker hub
  become: yes
  docker_image:
    name: myapp-cd
    repository: amineturki/cd
    tag: 7.0
    push: yes
