apiVersion: apps/v1
kind: Deployment
metadata:
  name: angular-deployment
  labels:
    app: angular-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: angular-app-pod
      app: demo-angular-app
  template:
    metadata:
      name: angular-app-pod
      labels:
        name: angular-app-pod
        app: demo-angular-app

    spec:
      containers:
      - name: angular
        image: amineturki/cd:latest
        ports:
        - containerPort: 80
