
- name: "current user"
  shell: "whoami"
  register: "output"
  become: yes
  become_user: cd-amine
- debug: var=output.stdout_lines

- name: "current directory"
  shell: "pwd"
  register: "output"
  become: yes
  become_user: cd-amine
- debug: var=output.stdout_lines

- name: "go to cd workspace"
  shell: "cd /var/lib/jenkins/workspace/cd/"
  become: yes
  become_user: cd-amine
  
- name: "current directory 2"
  shell: "pwd"
  register: "output"
  become: yes
  become_user: cd-amine
- debug: var=output.stdout_lines

- name: deploy app
  shell: kubectl  apply -f deployment-angular.yml
  become: yes
  become_user: cd-amine
# tasks file for kubernetes
