- name: "just execute a ls -lrt command"
  shell: "whoami"
  register: "output"
- debug: var=output.stdout_lines
#- name: deploy app
#  shell: kubectl  apply -f deployment-angular.yml
# tasks file for kubernetes
