
- name: "current user"
  shell: "whoami"
  register: "output"
  become: yes
  become_user: cd-amine
- debug: var=output.stdout_lines

- name: "current directory"
  shell: "pwd"
  register: "output"
  become: yes
  become_user: cd-amine
- debug: var=output.stdout_lines

- name: deploy the app
  shell: kubectl  apply -f deployment-angular.yml
  become: yes
  become_user: cd-amine
  
- name: service for the app
  shell: kubectl  apply -f service-angular-yml
  become: yes
  become_user: cd-amine  
# tasks file for kubernetes
