- name: What is my inventory_hostname
  debug: var={{inventory_hostname}}
- name: What is my ansible_hostname
  debug: var={{ansible_hostname}}
#- name: deploy app
#  shell: kubectl  apply -f deployment-angular.yml
# tasks file for kubernetes
